# Generated by Django 2.1.2 on 2018-10-03 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181003_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrelationship',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted')], default='invited', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(related_name='_user_friends_+', through='users.FriendRelationship', to=settings.AUTH_USER_MODEL),
        ),
    ]
